version: '2'

services:
  database:
    image: 'mysql:5.7.16'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
  system_dependencies: &base
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-dev
    environment:
      MIGRATION: 1
      RACK_ENV: development
      RAILS_ENV: development
      COMMAND: bin/rails s -b 0.0.0.0
    links:
      - database
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp
    stdin_open: true
    tty: true
  test:
    image: 'rails'
    command: bash -c "rails new app && cat"